### ISSUE TITLE
Keybindings in Command Palette don't show up

### ISSUE THREAD

**Issue by 50Wliu** [jglovier/fizzy#18]
![No keys](https://cloud.githubusercontent.com/assets/2766036/7760162/a3afd924-ffe6-11e4-8575-31d2cddc6c5e.png)

Fizzy 0.16.0, Atom 0.201.0-ba6e769, Ubuntu 15.04.

**Comment by 50Wliu** [comment]
This is actually an issue in core, so I'll close this in favor of atom/atom#6923.

**Comment by jglovier** [comment]
:+1: Thanks.
