### ISSUE TITLE
Deprecated selector in `fizzy/index.less`

### ISSUE THREAD

**Issue by andrew** [jglovier/fizzy#22]
In `fizzy/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.atom-text-editor,
:host` => `.atom-text-editor,atom-text-editor`

* `.atom-text-editor .invisible-character,
:host .invisible-character,
.atom-text-editor .indent-guide,
:host .indent-guide` => `.atom-text-editor .invisible-character,atom-text-editor .invisible-character,
.atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `.atom-text-editor .gutter,
:host .gutter` => `.atom-text-editor .gutter,atom-text-editor .gutter`

* `.atom-text-editor .gutter .line-number,
:host .gutter .line-number` => `.atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number`

* `.atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
.atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
.atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `.atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
.atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
.atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `.atom-text-editor .cursor,
:host .cursor` => `.atom-text-editor .cursor,atom-text-editor .cursor`

* `.atom-text-editor .selection .region,
:host .selection .region` => `.atom-text-editor .selection .region,atom-text-editor .selection .region`

* `.atom-text-editor .line-number.cursor-line-no-selection,
:host .line-number.cursor-line-no-selection` => `.atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line-number.cursor-line-no-selection`

* `.comment` => `.syntax--comment`

* `.entity` => `.syntax--entity`

* `.keyword` => `.syntax--keyword`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.constant` => `.syntax--constant`

* `.constant.numeric,
.constant.boolean` => `.syntax--constant.syntax--numeric,
.syntax--constant.syntax--boolean`

* `.variable` => `.syntax--variable`

* `.delimiter,
.brace` => `.syntax--delimiter,
.syntax--brace`

* `.delimiter.period` => `.syntax--delimiter.syntax--period`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.string` => `.syntax--string`

* `.string .constant.character.escape` => `.syntax--string .syntax--constant.syntax--character.syntax--escape`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded,
.string.regexp .string.regexp.arbitrary-repitition` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded,
.syntax--string.syntax--regexp .syntax--string.syntax--regexp.syntax--arbitrary-repitition`

* `.css .entity` => `.syntax--css .syntax--entity`

* `.css .property-name` => `.syntax--css .syntax--property-name`

* `.css .variable` => `.syntax--css .syntax--variable`

* `.css .constant,
.css .unit` => `.syntax--css .syntax--constant,
.syntax--css .syntax--unit`

* `.css .quoted` => `.syntax--css .syntax--quoted`

* `.html .tag,
.xml .tag` => `.syntax--html .syntax--tag,
.syntax--xml .syntax--tag`

* `.html .entity,
.xml .entity` => `.syntax--html .syntax--entity,
.syntax--xml .syntax--entity`

* `.html .entity.name,
.xml .entity.name` => `.syntax--html .syntax--entity.syntax--name,
.syntax--xml .syntax--entity.syntax--name`

* `.html .comment,
.xml .comment` => `.syntax--html .syntax--comment,
.syntax--xml .syntax--comment`

* `.html .attribute-name,
.xml .attribute-name` => `.syntax--html .syntax--attribute-name,
.syntax--xml .syntax--attribute-name`

* `.html .quoted,
.xml .quoted` => `.syntax--html .syntax--quoted,
.syntax--xml .syntax--quoted`

* `.html .quoted .punctuation,
.xml .quoted .punctuation` => `.syntax--html .syntax--quoted .syntax--punctuation,
.syntax--xml .syntax--quoted .syntax--punctuation`

* `.html .js .quoted,
.xml .js .quoted` => `.syntax--html .syntax--js .syntax--quoted,
.syntax--xml .syntax--js .syntax--quoted`

* `.gfm .link` => `.syntax--gfm .syntax--link`

* `.gfm .link .entity` => `.syntax--gfm .syntax--link .syntax--entity`

* `.gfm .link .link` => `.syntax--gfm .syntax--link .syntax--link`

* `.gfm .heading` => `.syntax--gfm .syntax--heading`

* `.gfm .list,
.gfm .hr` => `.syntax--gfm .syntax--list,
.syntax--gfm .syntax--hr`

* `.gfm .quote` => `.syntax--gfm .syntax--quote`

* `.gfm .raw` => `.syntax--gfm .syntax--raw`

* `.gfm .raw .support` => `.syntax--gfm .syntax--raw .syntax--support`

* `.json .punctuation` => `.syntax--json .syntax--punctuation`

* `.json .punctuation.separator` => `.syntax--json .syntax--punctuation.syntax--separator`

* `.json .quoted` => `.syntax--json .syntax--quoted`

* `.json .constant` => `.syntax--json .syntax--constant`

* `.yaml .entity.name` => `.syntax--yaml .syntax--entity.syntax--name`

* `.yaml .string .punctuation` => `.syntax--yaml .syntax--string .syntax--punctuation`

* `.ruby .entity.name` => `.syntax--ruby .syntax--entity.syntax--name`

* `.ruby .string` => `.syntax--ruby .syntax--string`

* `.erb .embedded.erb` => `.syntax--erb .syntax--embedded.syntax--erb`

* `.erb .embedded.erb .variable` => `.syntax--erb .syntax--embedded.syntax--erb .syntax--variable`

* `.erb .embedded.erb .punctuation` => `.syntax--erb .syntax--embedded.syntax--erb .syntax--punctuation`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pauloelias** [comment]
@andrew #23 fixes this and was recently merged in

**Comment by andrew** [comment]
Thanks!
