### ISSUE TITLE
Latest release disables all fonts 

### ISSUE THREAD

**Issue by jaredreich** [jglovier/fizzy#24]
Now no matter what, atom editor text is stuck to inconsolata. I know it's fizzy because this toggles as I switch from fizzy to other themes.

**Comment by jglovier** [comment]
Yeah, I set the fonts to my preference for the theme, but since it's just supposed to be a syntax theme I def shouldn't be doing that here in the package. Thanks for pointing it out.

**Comment by jaredreich** [comment]
Cool. Are you going to push this fix into a release?

**Comment by jglovier** [comment]
@jaredreich yes, it was pushed immediately after I made the commit, so the latest version fixes it. Just go to your Atom preferences and install the latest update.

**Comment by jaredreich** [comment]
Ah I see. Just noticed the last release push was 9 days ago so I didn't think a new version would be available on Atom. Thanks!
