### ISSUE TITLE
User specified fonts are not applied

### ISSUE THREAD

**Issue by NM-Clio** [jglovier/fizzy#7]
Under Atom v0.176.0 at least, the syntax theme enforces a particular font. Any font specified by the user in **Settings** is ignored.

**Comment by michelegera** [comment]
+1, I am on v0.178.0 on OS X Yosemite.

**Comment by sethlivingston** [comment]
Love this theme, but this is a show-stopper.

**Comment by jglovier** [comment]
This should now be fixed in `v0.21.0` (via https://github.com/jglovier/fizzy/commit/913dac34285ebce7017b13750411430e92f2a212). Sorry for the long delay on getting this fixed. :heart:
